# Generated by Django 5.2.7 on 2025-11-01 20:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('coordinator', 'Координатор'), ('engineer', 'Инженер'), ('viewer', 'Просмотрщик')], default='engineer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('success', 'Успешно'), ('failed', 'Ошибка')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.IntegerField(default=1)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'ordering': ['-last_attempt'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_type', models.CharField(choices=[('inspection', 'Обследование объекта'), ('meter_check', 'Проверка коммерческого учета'), ('maintenance', 'Техническое обслуживание'), ('repair', 'Ремонт'), ('emergency', 'Аварийная работа')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланирована'), ('assigned', 'Назначена'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=20)),
                ('object_address', models.CharField(max_length=500)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('planned_date', models.DateField()),
                ('planned_time_start', models.TimeField(blank=True, null=True)),
                ('planned_time_end', models.TimeField(blank=True, null=True)),
                ('meter_number', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на работу',
                'verbose_name_plural': 'Заявки на работу',
                'ordering': ['-planned_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_start_time', models.DateTimeField()),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено'), ('issues', 'Обнаружены проблемы'), ('rework', 'Требуется переделка')], default='in_progress', max_length=20)),
                ('work_description', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('meter_readings', models.TextField(blank=True)),
                ('meter_reading_date', models.DateField(blank=True, null=True)),
                ('work_quality', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_synced', models.BooleanField(default=False)),
                ('sync_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_results', to=settings.AUTH_USER_MODEL)),
                ('work_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='fieldwork_app.workrequest')),
            ],
            options={
                'verbose_name': 'Результат работы',
                'verbose_name_plural': 'Результаты работ',
            },
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='work_photos/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('is_synced', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fieldwork_app.workresult')),
            ],
            options={
                'verbose_name': 'Фотография работы',
                'verbose_name_plural': 'Фотографии работ',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('report', 'Отчет'), ('receipt', 'Квитанция'), ('contract', 'Контракт'), ('checklist', 'Чек-лист'), ('other', 'Другое')], max_length=20)),
                ('file', models.FileField(upload_to='work_documents/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('is_synced', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fieldwork_app.workresult')),
            ],
            options={
                'verbose_name': 'Документ работы',
                'verbose_name_plural': 'Документы работ',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkAct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act_number', models.CharField(max_length=50, unique=True)),
                ('act_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан'), ('archived', 'В архиве')], default='draft', max_length=20)),
                ('engineer_signature_required', models.BooleanField(default=True)),
                ('coordinator_signature_required', models.BooleanField(default=False)),
                ('engineer_signature_date', models.DateTimeField(blank=True, null=True)),
                ('coordinator_signature_date', models.DateTimeField(blank=True, null=True)),
                ('act_content', models.TextField()),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='act', to='fieldwork_app.workresult')),
            ],
            options={
                'verbose_name': 'Акт выполненной работы',
                'verbose_name_plural': 'Акты выполненных работ',
                'ordering': ['-act_date'],
            },
        ),
    ]
